---
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
extends:
  - xo-react
  - prettier
  - plugin:jest/recommended
  - prettier/react
env:
  es6: true
  jest: true
plugins:
  - prettier
  - jest
  - flowtype-errors
rules:
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  react/destructuring-assignment: false
  react/no-deprecated: false
  max-nested-callbacks:
  - error
  - 20
  flowtype-errors/show-errors: 2
globals:
  VERSION: true
overrides:
- files:
  - "*.spec.js"
  rules:
    react/prop-types: 0
