---
parser: babel-eslint
extends:
  - xo-react
  - prettier
  - plugin:jest/recommended
  - prettier/react
env:
  es6: true
  jest: true
plugins:
  - prettier
  - jest
rules:
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  max-nested-callbacks:
  - error
  - 20
globals:
  VERSION: true
