parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    modules: true
extends:
  - xo
  - xo-typescript
  - xo-react
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
  - plugin:jest/recommended
env:
  es6: true
  jest: true
  browser: true
plugins:
  - prettier
  - jest
rules:
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  max-nested-callbacks:
    - error
    - 20
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/promise-function-async': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/default-param-last': 1
  '@typescript-eslint/no-unsafe-call': 0
  '@typescript-eslint/no-unsafe-return': 0
  default-param-last: 0
globals:
  VERSION: true
overrides:
  - files:
      - '*.spec.js'
      - 'packages/test-utils/*.js'
    rules:
      react/prop-types: 0
  - files:
      - '*.js'
    rules:
      '@typescript-eslint/no-unsafe-member-access': 0
      '@typescript-eslint/no-unsafe-call': 0
      '@typescript-eslint/no-unsafe-return': 0
      '@typescript-eslint/prefer-readonly-parameter-types': 0
settings:
  react:
    version: 'detect'
