nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: 'https://raw.githubusercontent.com/gravitywelluk/yarn-plugin-postinstall/master/bundles/%40yarnpkg/plugin-postinstall.js'

yarnPath: .yarn/releases/yarn-3.1.0.cjs

# We need to run prettier to avoid unnecessary formatting changes to package.json (due to Yarn install).
postinstall: yarn setup && yarn prettier --write --parser json '**/package.json'
