packages:
  - packages/*
  - tooling/*
overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
patchedDependencies:
  cypress@13.6.4: patches/cypress@13.6.4.patch
allowBuilds:
  core-js: true
  cypress: true
  esbuild: true
peerDependencyRules:
  allowedVersions:
    'tsdown>typescript': '7'
