name: CI

description: Shared action to install dependencies

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Install
      run: pnpm install
      shell: bash
