name: 'Bundles'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/ci

      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: pnpm build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
